---
- name: Installing multiple users
  hosts: all
  become: true
  tasks:

  - name: Installing multiple users
    user: 
     name: "{{item}}"
     state: present
    with_items:
     - user1
     - user2
     - user3
     - user4
     - user5
